// vue-app/src/components/BookingAdd.vue
<template>
  <div class="hello">
    <h1>Add booking</h1>


    <form class="offset-4 col-md-4 text-left">
      <div class="form-group">
        <label>Contact Name</label>
        <input type="text" class="form-control" v-model="booking.contactName" />
      </div>

      <div class="form-group">
        <label>Contact Number</label>
        <input type="text" class="form-control" v-model="booking.contactNumber" />
      </div>

      <div class="form-group">
        <label>Party Size</label>
        <input type="number" class="form-control" v-model="booking.numberOfPeople" />
      </div>

      <div class="form-group">
        <label>Table Number</label>
        <input type="number" class="form-control" v-model="booking.tableNumber" />
      </div>

      <div class="form-group">
        <label>Booking Time</label>
        <input type="datetime-local" class="form-control" v-model="booking.bookingTime" />
      </div>

      <div class="text text-danger">
        {{response}}
      </div>

      <button type="button" class="btn btn-primary" v-on:click="saveData()">
        Save
      </button>
    </form>
  </div>
</template>

<script>
export default {
  name: "BookingAdd",
  props: {
    msg: String
  },
  data() {
    return {
      response: null,
      booking: {}
    };
  },
  methods: {
    saveData() {
      fetch("http://localhost:52363/booking", {
        method: "post",
        body: JSON.stringify(this.booking),
        headers: {
          "Content-Type": "application/json"
        }
      }).then(response => {
        if (response.status === 200) {
          console.log("yes");
          this.$router.push('/')
        } else {
          response.json().then(data => {
            this.response = data.message;
          });
        }
      });
    }
  },
  mounted() {}
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
.red {
  color: red;
}
.blue {
  color: blue;
}
</style>

// react-app/src/booking-add/BookingAdd.js
import React, {Component} from "react"

const config = require("../config");

class BookingAdd extends Component {

    constructor(props) {
        super(props);

        this.state = {
            booking: {}
        };

        this.handleChangeGeneric = this.handleChangeGeneric.bind(this);
        this.handleNameChange = this.handleNameChange.bind(this);
    }

    render() {
        return (
            <div>
                <h2>Add booking</h2>

                <form className="offset-4 col-md-4 text-left">

                    <div className={"form-group"}>
                        <label>Contact Name</label>
                        <input type="text" className="form-control" name="contactName"
                               onChange={this.handleNameChange}/>
                    </div>

                    <div className={"form-group"}>
                        <label>Contact Number</label>
                        <input type="text" className="form-control" name="contactNumber"
                               onChange={this.handleChangeGeneric}/>
                    </div>

                    <div className={"form-group"}>
                        <label>Number of People</label>
                        <input type="text" className="form-control" name="numberOfPeople"
                               onChange={this.handleChangeGeneric}/>
                    </div>

                    <div className={"form-group"}>
                        <label>Table Number</label>
                        <input type="number" className="form-control" name="tableNumber"
                               onChange={this.handleChangeGeneric}/>
                    </div>

                    <div className={"form-group"}>
                        <label>Booking Time</label>
                        <input type="datetime-local" className="form-control" name="bookingTime"
                               onChange={this.handleChangeGeneric}/>
                    </div>

                    <input className={"btn btn-primary"} type="button" value="Submit"
                           onClick={() => this.addBooking()}/>

                    <div className="text text-danger">{this.state.response}</div>

                </form>
            </div>
        )
    };

    addBooking() {
        console.log(this.state.booking);

        fetch(config.apiUrl + "booking", {
            method: "post",
            body: JSON.stringify(this.state.booking),
            headers: {
                'Content-type': 'application/json'
            }
        }).then(res => {
            if (res.status === 200) {
                console.log("success")
                this.props.history.push("/bookings")
            } else {
                res.json().then(text => {
                    this.setState({response: "An error occurred: " + text.message})
                });
            }
        })
    }

    handleNameChange(event) {
        let modified = this.state.booking;
        modified.contactName = event.target.value;
        this.setState({booking: modified})
    }

    handleChangeGeneric(event) {
        let modifiedItem = {...this.state.booking}; // copy the item
        modifiedItem[event.target.name] = event.target.value;

        console.log(`changing field ${event.target.name} to ${event.target.value}`);

        this.setState({booking: modifiedItem});

    }

}

export default BookingAdd;
